In [8]:
import geopandas as gpd
import pandas as pd

In [9]:
ejsm = gpd.read_file('Data/EJSM_Scores/3add6368-e61a-4279-8cc3-ad1ccb0eaadf202041-1-180j648.ou0r.shp')

In [10]:
print(ejsm)

      OBJECTID     Tract_1  CIscore  HazScore  HealthScor  SVscore  CCVscore  \
0            1  6037920336       10         3           1        4         2
1            2  6037920044        4         1           1        1         1
2            3  6037573003       13         5           3        3         2
3            4  6037571704       13         3           2        4         4
4            5  6037570403       17         5           3        5         4
...        ...         ...      ...       ...         ...      ...       ...
2338      2339  6037430302        6         2           1        1         2
2339      2340  6037430723       10         1           2        2         5
2340      2341  6037431100       14         5           2        3         4
2341      2342  6037533603       19         4           5        5         5
2342      2343  6037534101       17         5           5        5         2

        Shape__Are   Shape__Len  \
0     2.438560e+06  8124.373091
1     1.470811e+06  5545.298452
2     6.528168e+05  3310.743793
3     6.994011e+05  4113.477175
4     8.317839e+05  3887.000394
...            ...          ...
2338  2.837403e+06  8660.625349
2339  7.104454e+05  4760.545888
2340  4.412789e+06  9705.187477
2341  1.183445e+06  5970.437370
2342  7.432376e+05  5343.149124

                                               geometry
0     POLYGON ((-118.52876 34.38192, -118.52667 34.3...
1     POLYGON ((-118.50839 34.44845, -118.50816 34.4...
2     POLYGON ((-118.19925 33.79704, -118.19923 33.7...
3     POLYGON ((-118.18494 33.85434, -118.18493 33.8...
4     POLYGON ((-118.20057 33.88136, -118.20055 33.8...
...                                                 ...
2338  POLYGON ((-117.99173 34.15652, -117.99079 34.1...
2339  POLYGON ((-118.04961 34.13169, -118.04954 34.1...
2340  POLYGON ((-117.99875 34.14593, -117.99873 34.1...
2341  POLYGON ((-118.18743 33.97441, -118.18802 33.9...
2342  POLYGON ((-118.16365 33.97506, -118.16538 33.9...

[2343 rows x 10 columns]

In [11]:
type(ejsm)

geopandas.geodataframe.GeoDataFrame

In [12]:
ejsm.head()

,OBJECTID,Tract_1,CIscore,HazScore,HealthScor,SVscore,CCVscore,Shape__Are,Shape__Len,geometry
0,1,6037920336,10,3,1,4,2,2.438560e+06,8124.373091,"POLYGON ((-118.52876 34.38192, -118.52667 34.3..."
1,2,6037920044,4,1,1,1,1,1.470811e+06,5545.298452,"POLYGON ((-118.50839 34.44845, -118.50816 34.4..."
2,3,6037573003,13,5,3,3,2,6.528168e+05,3310.743793,"POLYGON ((-118.19925 33.79704, -118.19923 33.7..."
3,4,6037571704,13,3,2,4,4,6.994011e+05,4113.477175,"POLYGON ((-118.18494 33.85434, -118.18493 33.8..."
4,5,6037570403,17,5,3,5,4,8.317839e+05,3887.000394,"POLYGON ((-118.20057 33.88136, -118.20055 33.8..."

In [13]:
ejsm.tail()

,OBJECTID,Tract_1,CIscore,HazScore,HealthScor,SVscore,CCVscore,Shape__Are,Shape__Len,geometry
2338,2339,6037430302,6,2,1,1,2,2.837403e+06,8660.625349,"POLYGON ((-117.99173 34.15652, -117.99079 34.1..."
2339,2340,6037430723,10,1,2,2,5,7.104454e+05,4760.545888,"POLYGON ((-118.04961 34.13169, -118.04954 34.1..."
2340,2341,6037431100,14,5,2,3,4,4.412789e+06,9705.187477,"POLYGON ((-117.99875 34.14593, -117.99873 34.1..."
2341,2342,6037533603,19,4,5,5,5,1.183445e+06,5970.437370,"POLYGON ((-118.18743 33.97441, -118.18802 33.9..."
2342,2343,6037534101,17,5,5,5,2,7.432376e+05,5343.149124,"POLYGON ((-118.16365 33.97506, -118.16538 33.9..."

In [14]:
ejsm.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OBJECTID    2343 non-null   int64
 1   Tract_1     2343 non-null   int64
 2   CIscore     2343 non-null   int64
 3   HazScore    2343 non-null   int64
 4   HealthScor  2343 non-null   int64
 5   SVscore     2343 non-null   int64
 6   CCVscore    2343 non-null   int64
 7   Shape__Are  2343 non-null   float64
 8   Shape__Len  2343 non-null   float64
 9   geometry    2343 non-null   geometry
dtypes: float64(2), geometry(1), int64(7)
memory usage: 183.2 KB

In [26]:
ejsm.info(verbose=True, null_counts=True)

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OBJECTID    2343 non-null   int64
 1   Tract_1     2343 non-null   int64
 2   CIscore     2343 non-null   int64
 3   HazScore    2343 non-null   int64
 4   HealthScor  2343 non-null   int64
 5   SVscore     2343 non-null   int64
 6   CCVscore    2343 non-null   int64
 7   Shape__Are  2343 non-null   float64
 8   Shape__Len  2343 non-null   float64
 9   geometry    2343 non-null   geometry
dtypes: float64(2), geometry(1), int64(7)
memory usage: 183.2 KB

In [27]:
ejsm.Tract_1.head()

0    6037920336
1    6037920044
2    6037573003
3    6037571704
4    6037570403
Name: Tract_1, dtype: int64

In [39]:
ejsm = gpd.read_file(
    'Data/EJSM_Scores/3add6368-e61a-4279-8cc3-ad1ccb0eaadf202041-1-180j648.ou0r.shp',
    dtype=
    {
        'Tract_1':str,
    }
)

In [42]:
ejsm['Tract_1']=ejsm['Tract_1'].apply(lambda x: '{0:0>10}'.format(x))
print (ejsm)

      OBJECTID     Tract_1  CIscore  HazScore  HealthScor  SVscore  CCVscore  \
0            1  6037920336       10         3           1        4         2
1            2  6037920044        4         1           1        1         1
2            3  6037573003       13         5           3        3         2
3            4  6037571704       13         3           2        4         4
4            5  6037570403       17         5           3        5         4
...        ...         ...      ...       ...         ...      ...       ...
2338      2339  6037430302        6         2           1        1         2
2339      2340  6037430723       10         1           2        2         5
2340      2341  6037431100       14         5           2        3         4
2341      2342  6037533603       19         4           5        5         5
2342      2343  6037534101       17         5           5        5         2

        Shape__Are   Shape__Len  \
0     2.438560e+06  8124.373091
1     1.470811e+06  5545.298452
2     6.528168e+05  3310.743793
3     6.994011e+05  4113.477175
4     8.317839e+05  3887.000394
...            ...          ...
2338  2.837403e+06  8660.625349
2339  7.104454e+05  4760.545888
2340  4.412789e+06  9705.187477
2341  1.183445e+06  5970.437370
2342  7.432376e+05  5343.149124

                                               geometry
0     POLYGON ((-118.52876 34.38192, -118.52667 34.3...
1     POLYGON ((-118.50839 34.44845, -118.50816 34.4...
2     POLYGON ((-118.19925 33.79704, -118.19923 33.7...
3     POLYGON ((-118.18494 33.85434, -118.18493 33.8...
4     POLYGON ((-118.20057 33.88136, -118.20055 33.8...
...                                                 ...
2338  POLYGON ((-117.99173 34.15652, -117.99079 34.1...
2339  POLYGON ((-118.04961 34.13169, -118.04954 34.1...
2340  POLYGON ((-117.99875 34.14593, -117.99873 34.1...
2341  POLYGON ((-118.18743 33.97441, -118.18802 33.9...
2342  POLYGON ((-118.16365 33.97506, -118.16538 33.9...

[2343 rows x 10 columns]

In [40]:
ejsm.head()

,OBJECTID,Tract_1,CIscore,HazScore,HealthScor,SVscore,CCVscore,Shape__Are,Shape__Len,geometry
0,1,6037920336,10,3,1,4,2,2.438560e+06,8124.373091,"POLYGON ((-118.52876 34.38192, -118.52667 34.3..."
1,2,6037920044,4,1,1,1,1,1.470811e+06,5545.298452,"POLYGON ((-118.50839 34.44845, -118.50816 34.4..."
2,3,6037573003,13,5,3,3,2,6.528168e+05,3310.743793,"POLYGON ((-118.19925 33.79704, -118.19923 33.7..."
3,4,6037571704,13,3,2,4,4,6.994011e+05,4113.477175,"POLYGON ((-118.18494 33.85434, -118.18493 33.8..."
4,5,6037570403,17,5,3,5,4,8.317839e+05,3887.000394,"POLYGON ((-118.20057 33.88136, -118.20055 33.8..."

In [37]:
tracts = gpd.read_file('Data/CensusData2012/census tract (2012).shp')

In [38]:
tracts.info

<bound method DataFrame.info of                                slug                   set  \
0     06037101110-census-tract-2012  Census Tracts (2012)
1     06037101122-census-tract-2012  Census Tracts (2012)
2     06037101210-census-tract-2012  Census Tracts (2012)
3     06037101220-census-tract-2012  Census Tracts (2012)
4     06037101300-census-tract-2012  Census Tracts (2012)
...                             ...                   ...
2341  06037980031-census-tract-2012  Census Tracts (2012)
2342  06037980033-census-tract-2012  Census Tracts (2012)
2343  06037990100-census-tract-2012  Census Tracts (2012)
2344  06037990200-census-tract-2012  Census Tracts (2012)
2345  06037990300-census-tract-2012  Census Tracts (2012)

                     kind   external_i     name  \
0     Census Tract (2012)  06037101110  1011.10
1     Census Tract (2012)  06037101122  1011.22
2     Census Tract (2012)  06037101210  1012.10
3     Census Tract (2012)  06037101220  1012.20
4     Census Tract (2012)  06037101300     1013
...                   ...          ...      ...
2341  Census Tract (2012)  06037980031  9800.31
2342  Census Tract (2012)  06037980033  9800.33
2343  Census Tract (2012)  06037990100     9901
2344  Census Tract (2012)  06037990200     9902
2345  Census Tract (2012)  06037990300     9903

                           display_na     INTPTLAT NAME_1      INTPTLON  \
0     06037101110 Census Tract (2012)  +34.2594737   None  -118.2929869
1     06037101122 Census Tract (2012)  +34.2677213   None  -118.2901465
2     06037101210 Census Tract (2012)  +34.2529724   None  -118.2907309
3     06037101220 Census Tract (2012)  +34.2516085   None  -118.2816322
4     06037101300 Census Tract (2012)  +34.2487732   None  -118.2709976
...                               ...          ...    ...           ...
2341  06037980031 Census Tract (2012)  +33.7338344   None  -118.2627274
2342  06037980033 Census Tract (2012)  +33.7443155   None  -118.2203101
2343  06037990100 Census Tract (2012)  +33.9991909   None  -118.7921876
2344  06037990200 Census Tract (2012)  +33.9135868   None  -118.4928693
2345  06037990300 Census Tract (2012)  +33.6975355   None  -118.3467756

     FUNCSTAT        GEOID     AWATER COUNTYFP              NAMELSAD  MTFCC  \
0           S  06037101110          0      037  Census Tract 1011.10  G5020
1           S  06037101122          0      037  Census Tract 1011.22  G5020
2           S  06037101210          0      037  Census Tract 1012.10  G5020
3           S  06037101220          0      037  Census Tract 1012.20  G5020
4           S  06037101300          0      037     Census Tract 1013  G5020
...       ...          ...        ...      ...                   ...    ...
2341        S  06037980031   13318970      037  Census Tract 9800.31  G5020
2342        S  06037980033   16041385      037  Census Tract 9800.33  G5020
2343        S  06037990100  172776519      037     Census Tract 9901  G5020
2344        S  06037990200  207469766      037     Census Tract 9902  G5020
2345        S  06037990300  148837924      037     Census Tract 9903  G5020

     TRACTCE STATEFP     ALAND  \
0     101110      06   1142405
1     101122      06   2644042
2     101210      06    650691
3     101220      06    698969
4     101300      06   2581129
...      ...     ...       ...
2341  980031      06  12598244
2342  980033      06  12678792
2343  990100      06         0
2344  990200      06         0
2345  990300      06         0

                                               geometry
0     POLYGON ((-118.30229 34.25870, -118.30079 34.2...
1     POLYGON ((-118.30333 34.27354, -118.30318 34.2...
2     POLYGON ((-118.29945 34.25598, -118.28592 34.2...
3     POLYGON ((-118.28592 34.24896, -118.28592 34.2...
4     POLYGON ((-118.27247 34.23253, -118.27194 34.2...
...                                                 ...
2341  POLYGON ((-118.28530 33.70860, -118.28337 33.7...
2342  POLYGON ((-118.24463 33.71077, -118.23180 33.7...
2343  POLYGON ((-118.95114 33.99643, -118.95056 34.0...
2344  POLYGON ((-118.63168 34.00001, -118.63598 34.0...
2345  POLYGON ((-118.48228 33.74869, -118.47656 33.7...

[2346 rows x 19 columns]>